### ISSUE TITLE
Is ipad 2 2011 supported by any chance?

### ISSUE THREAD

**Issue by kirk86** [ben-z/free-sidecar#116]
Sorry to bother,
I thought I might ask just to make sure.
I see in the list of supported devices that ipad 2 2011 is not there, so I'm inferring that is not supported correct?

Thanks!

**Comment by ben-z** [comment]
It has to be able to run iPadOS 13

**Comment by kirk86** [comment]
@ben-z Thanks for the reply Ben, just a follow cause I have now idea how things work behind the scenes in this case, maybe you know this.
How's it possible for third party apps (duet, yam, etc.) to work seamlessly with older versions that run iOS 9.3.5, are they so much different than sidecar technology?

**Comment by ben-z** [comment]
I think Apple's goal is always to use the latest technology available. Perhaps the technologies that Sidecar required didn't exist in previous iOS versions. Sidecar used to support iPad Air 2 during the betas but they don't support it in the final release. This is probably due to the same reason -- iPad Air 2 probably required some compatibility code that they didn't want to keep around.
