### ISSUE TITLE
Macbook (10,1 - 10,2) - Unable to Connect - Misc error 32002

### ISSUE THREAD

**Issue by tmac1975** [ben-z/free-sidecar#13]
Please fill in the template below to speed up the review process:

**Mac model:** Macbook Pro early 2013 10,2 or 10,1
**iPad model:** iPad Pro 12.9" 3rd Gen

**Mac version** (optional): Catalina 10.15.2
**iPad version** (optional): iPad OS 13.3

**Comments:**
install worked as spec'd, tried connecting using two methods - USBC (iPad) - USB (MacBook) USBC (iPad) to HDMI (macbook)
Just ordered USBC to Thunderbolt adapter to see if this resolves the issue. Please confirm or advise.

<img width="427" alt="Screenshot 2019-11-16 at 11 26 40 am" src="https://user-images.githubusercontent.com/57832212/68992597-6e17e400-0865-11ea-9611-e59e2bae06c2.png">

Thanks! Great work BTW!

**Comment by ben-z** [comment]
As long as the iPad shows up in Finder as connected by USB and trusted, it should be able to connect. Note that since your setup involves an iPad Pro and an older Mac, the display quality might be suboptimal, in which case you should try some suggestions from here: https://github.com/ben-z/free-sidecar/issues/4#issuecomment-549176965

**Comment by tmac1975** [comment]
Thank you!!  That's the step I was missing - to connect and use finder to "trust" the iPad. Once I did that i connected without issue. Yes the quality isn't great so installing EasyRes to fix that.  Appreciate the fast response.  Works perfectly - Great work!!

**Comment by ben-z** [comment]
Awesome!
