### ISSUE TITLE
iPad 9.7'' 6th gen A1893 is not listed

### ISSUE THREAD

**Issue by emrdgrmnci** [ben-z/free-sidecar#136]
Please fill in the template below to speed up the review process:

Mac model: Macbook Pro 12,1
iPad model: A1893 (iPad 7,5)

Mac version: 10.15.7
iPad version: 14.2

Comments: I don't find my iPad model in enable device list.

**Comment by wsy** [comment]
According to [Apple](https://support.apple.com/en-us/HT210380), all iPad Pro models are eligible for SideCar. 
So you don't need to delete your iPad Pro from Apple's disallow list because it never existed in that list.
This FreeSidecar program only lists those models that are not allowed by Apple.
<img width="829" alt="截屏2020-11-16 17 47 11" src="https://user-images.githubusercontent.com/2684991/99237733-dbbd6e00-2833-11eb-9602-526f949a2824.png">
