### ISSUE TITLE
Display changed on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by ashleyengel** [ben-z/free-sidecar#152]
Please fill in the template below to speed up the review process:

**Mac model:** MacBook Air 13 inch, early 2015 running macOS Catalina 10.15.17

**Comments:**
So, I followed every step correctly. I had no issues or error messages pop up, I made sure to follow the special steps for the MacOS Catalina 10.15.4+, rebooted twice, and not only has my computer background changed entirely, the top bar that usually has the Bluetooth, WiFi, and airplay options has completely disappeared. The sidecar patch won’t work either, but that is the least of my worries at the moment. Some of my desktop documents have been deleted as well. Is there any way I can revert everything back? I have no backup in Time Machine and I am freaking out as I am a student and have lost a bit of my hard work. Any tips?

**Comment by ashleyengel** [comment]
Update: I tried to restore to the backup but didn’t work. I received no errors on step 8, but I see that this is the cause of most people’s issues. I still have system integrity disabled

**Comment by ashleyengel** [comment]
Second update: screen is now entirely black and will not respond to anything. Tried hard rebooting it, plugging it in, etc. It is technically “on” I think, because it is able to charge things via the USB port. Please please help ASAP

**Comment by ashleyengel** [comment]
Update again!! I got my computer back up with the same issues most people were having (menu bar not working, safari not working, apps crashing, etc.) HOWEVER when I go to revert to the backup file, I must have patched over the bak file because I get the message in terminal "no such file or directory" I would really like to start entirely over, however I can't because I must have messed up the backup file. Is there a way to get back?

**Comment by PMahar** [comment]
Devs will probably know more, but a somewhat similar issue happened to me and seems to occur when the framework isn't signed properly. Are you sure you ran `sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`? If not, you should be able to pop open recovery mode and use a terminal there. 

`amfi_get_out_of_my_way=0x1` should also show up when you run `nvram -p | grep "boot-args"`. If that's not there, do `sudo nvram boot-args="amfi_get_out_of_my_way=0x1 (and any other items you saw before that you recognize, separated by spaces)"` and reboot.

As for starting over, you can check for (more or less) certain if your backup file is modified by either looking at the "last modified" tag or by opening the free-sidecar app and seeing if any of the boxes are already checked. I don't know the legal/ethical specifics on sharing binaries like this otherwise I'd give you mine. Worst comes to worst, you can backup your important data though Finder if possible or otherwise use Paragon APFS on Windows and do a reinstall.

**Comment by simonfromla** [comment]
Tested on 10.15.7 and works fine.  

You should interpret step 8 as: If you have 10.15.4+, run `sudo nvram boot-args="amfi_get_out_of_my_way=0x1"`, followed by `sudo codesign -f -s - /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore`   

Then restart.  

Good luck.
