### ISSUE TITLE
[FEATURE REQUEST] Sidecar on iPhones

### ISSUE THREAD

**Issue by shortbow123** [ben-z/free-sidecar#24]
Okay, so iOS has the Sidecar.app bundled with it in /Applications on my iPhone 8 (iPhone10,1). I have been messing around with the Xcode project to get it to work. I know minimal Swift, so coding it is a bit of a struggle, but so far so good. I understand what most of the code does. But I have a few questions and maybe you can put my idea into actual work, but I was wondering where the identification number, Modelhex, Version and type come from. I am trying to get this to work mainly as a proof of concept and a flex on my broke android friends, lol. Help is very welcome!

**Comment by ben-z** [comment]
Interesting 🤔 How did you find out that Sidecar.app is bundled with iOS?

Which "identification number, Modelhex, Version and type" are you referring to?

**Comment by shortbow123** [comment]
![Screen Shot 2019-12-05 at 6 32 23 PM 3](https://user-images.githubusercontent.com/18692545/70290721-a425f500-178d-11ea-823d-b5a0a195a445.png)

The ones highlighted there. I jailbroke my phone with checkra1n and I found out when I was searching for an app I downloaded from the AppStore and I was browsing /Applications/ on Filza, I found Sidecar.app, it has the same Icon as on the iPad and in settings in Catalina. It has the executable inside it too with the full info.plist So I imagine iPadOS is just iOS 13 rebranded but still has ALL the same executables and such, either that or different firmwares bundled with it to save storage.

**Comment by shortbow123** [comment]
I can give all the help you need in development.

**Comment by ben-z** [comment]
Ooo interesting finding! I don't have an iPhone with checkra1n support... (I have iPhone 5 and XR, just outside the range of supported devices 😞.)

In the code, I split the identifier (e.g. `MacBookPro13,1`) into 3 parts:
1. `type` is the device type (e.g. `MacBookPro`)
1. `model` is the number before the comma (e.g. `13`)
1. `version` is the number after the comma (e.g. `1`)

To read/write the binary file `SidecarCore`, I first convert it into hex, then do a search/replace of the hex representation, then convert it back into binary and write to file. Any variables with `hex` in its name can be easily converted into ascii using any hex converter. For example, when `model` is `13`, `modelHex` is `3133`.

I'm not too sure how this information helps with enabling Sidecar on iOS devices though. Did you try running `Sidecar.app` on iOS to see if it opens? If it does then we need a way to trick the computer into thinking that the iOS device is an iPadOS device. When we achieve that, we probably need to change the output resolution so that it fits the smaller screen. I foresee that this would be difficult without access to the source code of Sidecar.

**Comment by shortbow123** [comment]
I did, but the only way right now is through the terminal and it gives me error 6, since I have to go into the .app directory and run the actual executable in there. On macOS it would popup as a window and like normal and have a bit whatever the app prints to the console in the terminal window, but on iOS you can't do that, so the system freaks. I have set the .app to have visibility and it is now on my home screen, but when I open it, there is only a blank screen, have to get around that. But, if I can get this working, since the block is actually on the mac, we might be able to do it without a jailbreak, because the app ONLY shows up when connected to a compatible Mac that recognizes it as a compatible device. I don't think we need to change any resolution output size since we do that already in macOS under screen settings. I need to add my iPhone 8 into the selection, so where are the type, model, and version stored within the code, if they are, I can't seem to find any sort of reference to them except for when I have xcode print out all the models.

**Comment by shortbow123** [comment]
![IMG_3061](https://user-images.githubusercontent.com/18692545/70296227-a6dd1600-179e-11ea-809b-c51223a4d802.PNG)

As you can see, my screen is a bit odd looking, by far the most rare thing on there is Sidecar.

**Comment by ben-z** [comment]
Ah nice intuition!

What this app (Free Sidecar) does is it scrambles a blacklist that Apple put into the `SidecarCore` file so that it does not block iPads that are in the blacklist. If you open `SidecarCore` with [iHex](https://apps.apple.com/us/app/ihex-hex-editor/id909566003?mt=12) and search for e.g. `iPad5,3` in the ascii section, you can see the blacklist. Because this is a blacklist, not a whitelist, (I think) the only way to get macOS to detect the iPhone is to change something on the iPhone side so that it shows up as an iPad on the Mac.

**Comment by shortbow123** [comment]
Okay, with jailbreak I may be able to do that, but, since the app is present I may be able to list all launch daemons and services running to see if it is listening for a sidecar connection. To enable the icon, I had to change some stuff in the info.plist file so it would show the app icon even when the app doesn't want to be shown. pretty interesting.

**Comment by ben-z** [comment]
Now we are venturing into an area that I'm unfamiliar with. I also don't have an iOS device that I can jailbreak and fiddle around with. But let me know if you make any progress on this! It's pretty intriguing.

**Comment by shortbow123** [comment]
Okay, I haven't really messed with launch daemons either, but if you have any suggestions on things to try on the iOS end, don't hesitate to respond. I think we are very close.

**Comment by ben-z** [comment]
Probably my last suggestion:

Have you tried jailbreak apps like http://cydia.saurik.com/package/net.85819.ios.otrlocation/? It seems to allow for device model spoofing. Not sure if it can make an iPhone appear as an iPad though.

This is from a reddit post: https://www.reddit.com/r/jailbreak/comments/8by2q4/tutorial_enable_instagrams_new_focus_camera_mode/?st=JFZ6WIAI&sh=75ce1308

**Comment by shortbow123** [comment]
Okay, thanks, I am looking and there are 2 services running on my iPhone from Sidecar, com.apple.sidecar-relay and com.apple.sidecar, the last one I am wondering if it is up because I messed with it or if it is always running

**Comment by 916253** [comment]
have you found anything else out on this? i'd be interested to see

**Comment by shortbow123** [comment]
No, I haven’t been focusing on it much, but I’m trying to figure out where
the detection is on the iOS side and how to correctly start the processes,
I need a jailbroken iPad compatible with iPadOS to be 100% sure, haven’t
been able to get one yet tho.

**Comment by ben-z** [comment]
@shortbow123 #43 appears to be related

**Comment by rullinoiz** [comment]
sorry for the necropost, but i found out that using macOS, right clicking on the desktop, and pressing import from iphone actually opens the sidecar app on the iphone

**Comment by akasshell** [comment]
> sorry for the necropost, but i found out that using macOS, right clicking on the desktop, and pressing import from iphone actually opens the sidecar app on the iphone

How did you do it? , thank you so much for the answer, I'm trying to do the same

**Comment by rullinoiz** [comment]
> > sorry for the necropost, but i found out that using macOS, right clicking on the desktop, and pressing import from iphone actually opens the sidecar app on the iphone
> 
> How did you do it? , thank you so much for the answer, I'm trying to do the same

i wasn't that clear, it opens the sidecar app but not for screen mirroring. once you actually finish taking a photo it closes sidecar
