### ISSUE TITLE
Does not work on MacOS 10.15.2 

### ISSUE THREAD

**Issue by JamesThorntonAlpha** [ben-z/free-sidecar#31]
Hi Ben, I'm trying to use this on MacOS 15.2 with an early 2015 MacBook Pro but when you click the 'Enable MacBookPro12,1' it goes clear and then goes back to orange.  Maybe there has been a change to the SidecarCore file?

**Comment by ben-z** [comment]
Oh snaps. That sounds like it! I won’t be able to access my computer until Jan 5. It probably won’t be fixed until then unless someone submits a PR. If you are adventurous enough and are comfortable with hex editors, feel free to search for “MacBookPro12,1” in the ascii representation of the SidecarCore file. Then change it to something random such as “MacBookPro12,0”. You can do this using the iHex editor.

**Comment by ben-z** [comment]
On a second thought, if the method described above works, then the app should be able to un-blacklist the device. I’ll have to take a look at the SidecarCore in 10.15.2 when I get access to my computer.

**Comment by JamesThorntonAlpha** [comment]
This worked a charm, thanks Ben!

**Comment by ndk0204** [comment]
Hi Ben,

I just tried using SideCar and it is in System Preferences, but similar to @JamesThorntonAlpha 's original problem, there are no devices visible in the dropdown menu. Similar to @JamesThorntonAlpha , I am also on macOS 10.15.2, which is probably the issue here.

Will you be releasing a newer version of Free Sidecar that automatically implements the changes you mentioned above? Unfortunately, I'm not very experienced in the field of using hex editors. :(

Many thanks in advance.

**Comment by ben-z** [comment]
I am not able to reproduce this problem on 10.15.2 (when following the instructions):

> when you click the 'Enable MacBookPro12,1' it goes clear and then goes back to orange

@JamesThorntonAlpha I'm suspecting that the original problem that you saw was due to the lack of write permissions on the `SidecarCore` that you selected. Perhaps I should make the instructions more clear that the user should select the `SidecarCore` file in `~/Downloads` instead of the one in `/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/`.

@ndk0204 Are you seeing the same problem that JamesThorntonAlpha reported, where "when you click the 'Enable MacBookPro12,1' it goes clear and then goes back to orange". Or are you just not seeing devices in the dropdown menu? If it's the latter please refer to the troubleshooting steps outlined in #27.

**Comment by JamesThorntonAlpha** [comment]
Ahhhh @ben-z I imagine that that is exactly what was wrong! User error, always the way! Thanks for your help!
