### ISSUE TITLE
Bad picture quality over wired connection

### ISSUE THREAD

**Issue by claxonberlin** [ben-z/free-sidecar#4]
**Mac model: ** MBPro 15 inch, Late 2013 with nVidia GPU
**iPad model: ** iPad Pro 12,9 inch (3rd generation)

**Mac version** (optional): 10.15.1
**iPad version** (optional): 13.2

Hi

I was wondering if it's a possibility that a wired connection also gives bad picture quality. My iPad screen is visible but there's stripey flickering artifacts and colours are washed out.

I turned off wireless connections. I've trusted my iPad via Finder. I'm 100% certain my connection is over cable (USB-A → USB-C).

One thing I can think off is that during the patching process, I didn't enable my iPad version in step 4. (I did enable the correct Macbook version)

Could that have been the problem?

Thank you for making such a big effort in helping us out!

**Comment by ben-z** [comment]
Since your iPad is supported officially, you don't need to enable Sidecar for your iPad explicitly.

I'm suspecting that the bad picture quality is due to the lack of HEVC encoder/decoder in the MBP '13—the Mac tries to send high quality images to the iPad but the computer is not able to keep up with such high quality. This might explain why the image quality is better if used with older iPads.

One possible solution (I don't have the setup to try this) might be to lower the resolution of the iPad display. If the system preferences pane doesn't let you do this, you can do this through apps like [easyres](https://apps.apple.com/app/easyres/id688211836?ls=1&mt=12).

**Comment by Tof32** [comment]
Hello ben-z,

I want to thank you for your tool, it's really great !
I'm with a MBP 15' mid 2012 and iPad Pro 11'.
I've the same poor quality described by clausbertels.
Tried easyres but there's no possibility to change resolution for the iPad screen it's stuck with Retina (2x) 1116 x 756.

If you have another idea, I'll give it a try ;-)

Thanks again for all !

**Comment by ben-z** [comment]
Ah true. easyres seems to not show additional resolutions. I'm currently unaware of a workaround...

**Comment by patricksmms** [comment]
I have the same issue with my MBP 11.1. Tried to connect with wire, didn't help. So I'm back to using duet display.

**Comment by emhriv** [comment]
same issue with mid 2012 MacBook Pro Retina 10,1. Would love someone to find a solution.

**Comment by Vaultnaemsae** [comment]
Exactly the same issue here on a mid-2015 MacBook Pro Retina 15" with an iPad Pro 10.5" on wired connection.

Patched successfully but the quality on the iPad display is woeful. I'm going back to using Luna Display.

**Comment by roygkov** [comment]
Hi everyone!
Same for me on mid-2015 MacBook Pro Retina 15 " w/ iPad Pro 2019 11" =(
I've tried using the easyres app but unfortunately it didn't work for me..
BTW, I noticed that the easyres app show me that iPad has a 19 "external (null) and only one resolution 1116 x 756, instead of 11". Maybe that's a case?

**Comment by StefanLobbenmeier** [comment]
I have the same issue that the easyres app does not show the correct display size. I also can not reduce the iPad resolution.

**Comment by Lownin** [comment]
I have the same issue
2015 15”  MacBook Pro
2019 iPad mini 5
