### ISSUE TITLE
Screen With Noise

### ISSUE THREAD

**Issue by mucan54** [ben-z/free-sidecar#97]
Mac model:MacBookAir6,2
iPad model:ipad 7

Mac version: Catalina 10.15.4
iPad version: 13.4

I'm not sure that is about the quality because, it sometimes looks normal when the color of screen mostly white. But darker colors it looks like noisy.

[ScreenShot](https://i.paste.pics/b5485504b315a2aaf8b8556c216e0640.png)

**Comment by ben-z** [comment]
This happens mainly with old macs + new ipads combinations. There have been a couple of issues about this but there's no clear solution.

**Comment by mucan54** [comment]
Is that can be about refresh rate of old Macs, because everything looks good colors, speed, but noise appears. Maybe it is about the Hz value and we can not change it on sidecar.

**Comment by ben-z** [comment]
Something to do with the lack of hardware HEVC encoding/decoding support on older macs

**Comment by Javibu5** [comment]
Hello, the same happened to me.
Mac model:MacBookPro 9,2
iPad model: ipad pro

Mac version: Catalina 10.15.4
iPad version: 13.4

**Comment by velanche** [comment]
Hello There:
Yep, I’m also getting a bit of noise on my iPad Pro 3rd Gen 12.9.  It’s really pronounced when I move the cursor via my trackpad.

I’m on MacOS Catalina 10.15.4.

Otherwise, I appreciate this; ingenious.

Will this noise potentially have an adverse effect on my hardware if I were to go with it?
V.

**Comment by CPS2020** [comment]
Hi all

Great job on getting SideCar to work on older Macs. Very cool!

Followed the instructions and needed SIP disabled as well as the NVRAM mod. SIP can not be enabled, otherwise the system does not work - just repeating what was found out by others.

Mac model: MacBookPro11,1
iPad model: iPad6,3 [wrong iPad reference removed]

Mac version: Catalina 10.15.5 beta 5 (just updated today)
iPad version: 13.5

I also have the screen jitter on the iPad Pro, primarily visible on solid colours "jitter" when the mouse is moved - but also visible when the mouse is left alone. To be honest, not really useable like that in the long term. Be great to have a solution for this, but if it's indeed lack of HVEC then maybe there will be no fix.

Cheers,
Claus.

**Comment by lincolnaleixo** [comment]
Happening with me as well
Macbook 11,5
iPad Pro 9.7
